name: Build, Test and Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build the project (again for deploy)
        run: ./gradlew build --no-daemon

      - name: kill old app
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no root@45.9.40.117 'pkill -f docker-file-test-app-0.0.1-SNAPSHOT.jar'

      - name: Copy files to remote server
        run: |
          scp -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no build/libs/docker-file-test-app-0.0.1-SNAPSHOT.jar root@45.9.40.117:testCd/

      - name: run new app
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} -o StrictHostKeyChecking=no root@45.9.40.117 'nohup java -jar testCd/docker-file-test-app-0.0.1-SNAPSHOT.jar > app.log 2>&1'

