name: CI/CD for Spring Boot App using Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Restart application
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}
          cd ${{ secrets.VPS_DEPLOY_PATH }}
          pkill -f 'docker-file-test-app-0.0.1-SNAPSHOT.jar' || true
          git pull
          nohup java -jar build/libs/docker-file-test-app-0.0.1-SNAPSHOT.jar > app.log 2>&1 &