name: Build, Test and Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.0'

      - name: Build project
        run: ./gradlew build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.0'

      - name: Run tests
        run: ./gradlew test --no-daemon

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: '8.0'

      - name: Build the project (again for deploy)
        run: ./gradlew build --no-daemon

      - name: Copy files to remote server
        run: |
          scp -i ${{ secrets.DEPLOY_KEY }} build/libs/docker-file-test-app-0.0.1-SNAPSHOT.jar root@45.9.40.117:/root/testCd/

      - name: SSH into remote server and restart the app
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} root@45.9.40.117 'sudo systemctl restart your-app.service'
