name: CI/CD for Spring Boot App using Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: chmod for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          APP_NAME: "spring-app.jar"
        run: |
          echo "${SSH_KEY}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${USER}@${HOST} "pkill -f ${APP_NAME} || true"
          scp -i key.pem build/libs/*.jar ${USER}@${HOST}:/home/${USER}/${APP_NAME}
          ssh -i key.pem ${USER}@${HOST} "nohup java -jar /home/${USER}/${APP_NAME} &"